### ISSUE TITLE
How to animate static mesh for rendering

### ISSUE THREAD

**Issue by 3Der1999** [openxrlab/xrfeitoria#23]
Thanks for your work! I find in `07_amass.py`, skeletal .fbx can be animated. But I only have static mesh(.obj) and smpl parameter, could you tell me how to animate static mesh for rendering? The methods I found on the Internet are all through the gui operation, while I have lots of mesh.
Thanks!

**Comment by HaiyiMei** [comment]
Do you wanna render a mesh sequence? `.obj` file for per frame?

**Comment by 3Der1999** [comment]
No, meshes are independent(e.g. Thumman dataset). I want to render each mesh animated by some motion sequences(e.g. running actor_001, running actor_002, walking actor_001, ...)

**Comment by HaiyiMei** [comment]
Well, in the current pipeline of XRFeitoria (graphics pipeline), it's impossible to drive non-skeletal meshes. Maybe you need to do skeleton binding first. But it's a tough task for reconstructed mesh due to its irregular topology. Or you can find some 4D meshes (mesh sequence).
To be noticed, you may consider using a NeRF-based method to drive your meshes along with SMPL/SMPLX parameters.

**Comment by 3Der1999** [comment]
Thanks for your advice!
